pub mod auth;
pub mod crypto;
pub mod error;
pub mod hash;
pub mod keys;
pub mod liquidity;
pub mod multipair;
pub mod types;

pub use auth::{
    CONTROL_PLANE_TOKEN_ENV, RECOVERY_AUTH_HEADER, constant_time_eq, derive_recovery_auth_tag,
    extract_bearer_token, format_bearer_token,
};
pub use crypto::{
    FeeOutputNoteInput, HeartbeatCoverOrder, NoteConsolidationCommitmentRoots,
    SettlementOutputWithdrawalMessage, SettlementOutputWithdrawalPlanRequest,
    Strk20ExitClaimMessage, admission_proof_message_hash_for_program,
    admission_proof_message_hash_from_statement, auction_admission_root,
    auction_result_proof_message_hash_for_program,
    auction_result_proof_message_hash_from_statement, build_admission_serialized_input,
    build_auction_result_serialized_input, build_deposit_note, build_deposit_submission_plan,
    build_fee_output_note, build_heartbeat_cover_orders, build_liquidity_position_serialized_input,
    build_multi_pair_serialized_input, build_note_consolidation_serialized_input,
    build_note_consolidation_submission_plan, build_order_submission, build_output_note,
    build_renewal_parent_cancel_submission_plan,
    build_settlement_output_withdrawal_serialized_input,
    build_settlement_output_withdrawal_submission_plan,
    build_settlement_output_withdrawal_submission_plan_from_witness,
    build_settlement_submission_plan, build_settlement_witness, build_stwo_serialized_input,
    create_liquidity_attribution_artifact, create_liquidity_position_ingress_receipt,
    create_order_ingress_receipt, create_recovery_artifact, decrypt_liquidity_attribution_artifact,
    decrypt_note_for_owner, decrypt_order_bundle, decrypt_order_share,
    decrypt_output_note_for_owner, decrypt_output_recovery_record,
    decrypt_recovery_artifact_payload, deposit_note_membership_witnesses_for_chain,
    deposit_root_from_note, derive_account_id, derive_order_cancellation_auth_tag,
    derive_order_cancellation_secret, derive_order_cancellation_tag,
    derive_order_execution_report_auth_tag, encrypt_note_for_owner, encrypt_output_note_for_owner,
    encrypt_output_recovery_record, encrypted_note_activation_commitment,
    funding_commitment_for_deposit, heartbeat_cover_order_commitments, heartbeat_cover_order_count,
    liquidity_band_attribution_commitment, liquidity_position_lifecycle_id,
    liquidity_position_proof_message_hash_for_program,
    liquidity_position_proof_message_hash_from_statement, liquidity_position_transition_commitment,
    liquidity_position_transition_witness_payload_commitment, native_admission_message_hash,
    native_auction_result_message_hash, native_liquidity_position_message_hash,
    native_note_consolidation_message_hash, native_nullifier_message_hash,
    native_renewal_message_hash, native_settlement_input_membership_message_hash,
    native_settlement_message_hash, native_settlement_order_message_hash,
    native_settlement_output_recovery_message_hash,
    native_settlement_output_withdrawal_message_hash, note_consolidation_commitment,
    note_consolidation_commitment_from_roots, note_consolidation_proof_message_hash_for_program,
    note_consolidation_proof_message_hash_from_statement,
    note_recognition_public_key_from_raw_key_hex, nullifier_proof_message_hash_for_program,
    nullifier_proof_message_hash_from_statement,
    nullifier_sparse_update_witnesses_for_consumed_inputs,
    nullifier_sparse_update_witnesses_for_nullifiers, output_note_merkle_proof,
    output_note_merkle_root, output_note_metadata_commitment,
    output_recovery_key_tag_for_spend_authority, private_execution_key_registry_fingerprint,
    private_order_payload_commitment, proof_artifact_commitment, reconstruct_order_from_shares,
    renewal_child_uses_from_matched_witnesses, renewal_parent_cancel_marker_message_hash,
    renewal_proof_message_hash_for_program, renewal_proof_message_hash_from_statement,
    renewal_relay_package_registration_message_hash,
    renewal_sparse_witness_for_parent_cancel_marker, renewal_sparse_witnesses_for_child_uses,
    root_only_settlement_commitments, sanitize_order_submission_for_coordinator,
    settlement_input_membership_proof_message_hash_for_program,
    settlement_input_membership_proof_message_hash_from_statement,
    settlement_liquidity_position_transition_root, settlement_note_root_after_deposit_roots,
    settlement_nullifier_root_after_history, settlement_order_proof_message_hash_for_program,
    settlement_order_proof_message_hash_from_statement,
    settlement_output_recovery_proof_message_hash_for_program,
    settlement_output_recovery_proof_message_hash_from_statement,
    settlement_output_withdrawal_commitment, settlement_output_withdrawal_message_hash,
    settlement_output_withdrawal_proof_message_hash_for_program, settlement_proof_message_hash,
    settlement_proof_message_hash_for_program, settlement_proof_message_hash_from_statement,
    settlement_state_transition_root, settlement_transcript_commitment,
    sign_note_consolidation_authorization, sign_order_authorization,
    sign_renewal_relay_package_authorization, sign_settlement_output_withdrawal_witness,
    sign_strk20_exit_claim_authorization, strk20_exit_claim_message_hash,
    validate_liquidity_attribution_receipt,
    validate_liquidity_position_ingress_receipt_for_manifest,
    validate_liquidity_position_ingress_receipt_for_manifest_with_secrets,
    validate_order_ingress_receipt_for_manifest,
    validate_order_ingress_receipt_for_manifest_with_secrets,
    validate_private_execution_key_registry_pin, validate_private_order_authorization,
    verify_liquidity_position_ingress_receipt,
    verify_liquidity_position_ingress_receipt_with_secrets, verify_order_ingress_receipt,
    verify_order_ingress_receipt_with_secrets, verify_output_note_membership,
    verify_renewal_relay_package_authorization,
};
pub use error::ProtocolError;
pub use keys::{RecoverySeed, UserKeys, derive_user_keys};
pub use liquidity::{
    LIQUIDITY_POSITION_SPARSE_TREE_DEPTH, LiquidityPositionCloseResult,
    LiquidityPositionCurveSlice, LiquidityPositionLifecycleAuthorization,
    LiquidityPositionMarketContext, LiquidityPositionOpenFunding, LiquidityPositionProofWitness,
    LiquidityPositionSettlementFill, LiquidityPositionSparseUpdateWitness, LiquidityPositionState,
    LiquidityPositionStateUpdate, LiquidityPositionTransitionWitness, LiquidityRewardAssessment,
    LiquidityRewardEntry, LiquidityRewardEpoch, LiquidityRewardPolicy,
    VerifiedLiquidityPositionProof, VerifiedLiquidityPositionTransition,
    apply_liquidity_position_fill, assess_liquidity_reward, build_liquidity_reward_entry,
    build_liquidity_reward_epoch, close_liquidity_position, derive_liquidity_position_curve_slice,
    liquidity_position_nullifier, liquidity_position_private_authority,
    liquidity_position_root_transition, liquidity_position_transition_message_hash,
    liquidity_position_transition_summary_root, liquidity_reward_entry_commitment,
    liquidity_reward_epoch_root, open_liquidity_position, reconfigure_liquidity_position,
    sign_liquidity_position_transition, verify_liquidity_position_proof_witness,
    verify_liquidity_position_state_update, verify_liquidity_position_transition_authorization,
    verify_liquidity_position_transition_witness,
};
pub use multipair::{
    MAX_MULTI_PAIR_ASSET_DELTAS, MAX_MULTI_PAIR_ASSETS, MAX_MULTI_PAIR_CANDIDATE_SOLUTIONS,
    MAX_MULTI_PAIR_FILLS, MultiPairAssetDelta, MultiPairAssetDeltaDirection,
    MultiPairAssetDeltaSource, MultiPairCandidateSolution, MultiPairFeasibilityProblem,
    MultiPairFeasibilityReport, MultiPairFill, MultiPairObjectiveWeight,
    MultiPairOptimalityProblem, MultiPairOptimalityReport, verify_multi_pair_feasibility,
    verify_multi_pair_optimality,
};
pub use types::{
    ARTIFACT_AGGREGATION_POLICY_VERSION, ArtifactAggregationPolicy, AssetId, AuctionOrderWitness,
    Batch, BatchId, BatchLiquidityReport, BatchOrderSet, BatchShareContributions, BatchStatus,
    BatchSummary, ClaimWindowPolicy, ConsumedInput, CoordinatorStatus, DecryptedOrderShare,
    DeploymentContracts, DeploymentManifest, DeploymentMetadata, DeploymentProofConfig,
    DeploymentRoles, DeploymentRuntime, DepositActivationRecord, DepositActivationRecordList,
    DepositCallArguments, DepositConfirmationList, DepositConfirmationRequest, DepositIntent,
    DepositSubmissionPlan, DepositSyncStatus, EncryptedBlob, EncryptedLiquidityAttributionArtifact,
    EncryptedRecoveryPayload, FeeEntry, FundingRailAssetConfig, FundingRailConfig, FundingRailKind,
    LIQUIDITY_POSITION_FIELD_COUNT, LIQUIDITY_POSITION_VERSION, LiquidityAttributionArtifactList,
    LiquidityAttributionBundle, LiquidityAttributionPlaintext, LiquidityAttributionReceipt,
    LiquidityBandAttribution, LiquidityBandFillAttribution, LiquidityCurve, LiquidityCurvePoint,
    LiquidityPositionBacking, LiquidityPositionCommitment, LiquidityPositionCurveKind,
    LiquidityPositionCurvePolicy, LiquidityPositionFillDelta, LiquidityPositionIngressReceipt,
    LiquidityPositionLifecycleAccepted, LiquidityPositionLifecycleReport,
    LiquidityPositionLifecycleSubmission, LiquidityPositionOracleGuard,
    LiquidityPositionRootTransition, LiquidityPositionRotationPolicy, LiquidityPositionStatus,
    LiquidityPositionTransitionKind, MAX_LIQUIDITY_POSITION_ROTATION_BPS, MatchedOrder,
    MatchedOrderWitness, MultiPairArtifactBundleList, MultiPairArtifactBundleSummary, Note,
    NoteCommitment, NoteConsolidationCallArguments, NoteConsolidationSubmissionPlan,
    NoteConsolidationWitness, NoteMembershipKind, NoteMembershipWitness, Nullifier,
    NullifierHistoryBatch, NullifierSparseUpdateWitness, OnchainSubmissionRecord,
    OrderCancellationAccepted, OrderCancellationRequest, OrderCommitment, OrderExecutionReport,
    OrderIngressClientTelemetry, OrderIngressReceipt, OrderIngressReceiptAttestation, OrderIntent,
    OrderShare, OrderShareBundle, OrderSide, OrderSubmission, OrderSubmissionAccepted, OrderType,
    OutputCiphertextBundle, OutputNoteMerkleProof, OutputNoteRecord, OutputRecoveryRecord,
    OwnedOutputNotePayload, PairId, PreparedBatchStatus, PrivateExecutionKeyPrivateConfig,
    PrivateExecutionKeyPublicConfig, PrivateExecutionKeyRegistry, PrivateLiquidityPosition,
    PrivateOrderPayload, PrivateSettlementOutputRecoveryRecord, PrivateSettlementReport,
    PrivateSettlementReportQuery, ProductAssetConfig, ProductConfig, ProductPairConfig,
    ProofArtifactRecord, ProofJobStatus, PublicBatchSummary, PublicSettlementTranscript,
    PublishedBatchArtifactList, PublishedBatchArtifactSummary, PublishedBatchArtifacts,
    RENEWAL_PARENT_CANCEL_DOMAIN_HEX, RecoveryArtifact, RecoveryArtifactKind, RecoveryArtifactList,
    RecoveryArtifactUpload, RelayMode, RenewalCancelMarkerList, RenewalCancelMarkerRecord,
    RenewalChildUse, RenewalParentCancelCallArguments, RenewalParentCancelPlanRequest,
    RenewalParentCancelSubmissionPlan, RenewalStateHistoryBatch, RootOnlySettlementCommitments,
    SPEND_AUTHORITY_DOMAIN_HEX, SPEND_AUTHORIZATION_TAG_DOMAIN_HEX, SettlementCallArguments,
    SettlementOutputWithdrawalCallArguments, SettlementOutputWithdrawalSubmissionPlan,
    SettlementOutputWithdrawalWitness, SettlementRootHistoryArchive, SettlementRootHistoryBatch,
    SettlementSubmissionPlan, SettlementTimestampUpdate, SettlementTranscript, SettlementWitness,
    SpendAuthorization, StarknetCall, StarknetPrivacyFundingRail,
    SubmittedLiquidityPositionLifecycleRecord, SubmittedOrderRecord, TimeInForce,
    TranscriptShapeMetadata, TrustedLiquidityPositionIngressRequest,
    TrustedLiquidityPositionIngressResponse, TrustedOrderIngressRequest,
    TrustedOrderIngressResponse, WalletEvent, WalletEventKind, WalletSnapshot,
    WithdrawalAmountBucketPlan, WithdrawalAmountBucketPolicy, WithdrawalWindowPlan,
    artifact_bundle_padded_count, artifact_epoch_bucket_end, artifact_epoch_bucket_start,
    asset_amount_scale, base_amount_affordable_for_quote, build_spend_authorization,
    count_bucket_label, default_pair_fee_bps, default_withdrawal_amount_buckets,
    funding_input_set_commitment, funding_nullifier_set_commitment, is_conversion_pair,
    known_asset_decimals, nullifier_from_note_secret, output_bundle_bucket_size,
    output_bundle_count_bucket_label, plan_withdrawal_amount_bucket, plan_withdrawal_window,
    quote_amount_for_base_amount, renewal_cancel_auth_key_felt_for_parent_from_raw_key_hex,
    renewal_cancel_auth_key_felt_from_raw_key_hex,
    renewal_cancel_authority_for_parent_from_raw_key_hex,
    renewal_cancel_authority_from_raw_key_hex,
    renewal_cancel_authority_from_renewal_cancel_auth_key_felt, renewal_child_nullifier,
    renewal_parent_cancel_marker, renewal_parent_commitment, renewal_parent_secret_commitment,
    spend_auth_key_felt_from_raw_key_hex, spend_authority_from_raw_key_hex,
    spend_authority_from_spend_auth_key_felt, spend_authorization_tag, transcript_shape_metadata,
    validate_transcript_shape_policy, verify_spend_authorization,
    withdraw_auth_key_felt_from_raw_key_hex, withdraw_authority_from_raw_key_hex,
    withdraw_authority_from_withdraw_auth_key_felt,
};
