pub mod auth;
pub mod crypto;
pub mod error;
pub mod hash;
pub mod keys;
pub mod types;

pub use auth::{
    CONTROL_PLANE_TOKEN_ENV, RECOVERY_AUTH_HEADER, constant_time_eq, derive_recovery_auth_tag,
    extract_bearer_token, format_bearer_token,
};
pub use crypto::{
    HeartbeatCoverOrder, NoteConsolidationCommitmentRoots, SettlementOutputWithdrawalMessage,
    SettlementOutputWithdrawalPlanRequest, admission_proof_message_hash_for_program,
    admission_proof_message_hash_from_statement, auction_admission_root,
    auction_result_proof_message_hash_for_program,
    auction_result_proof_message_hash_from_statement, build_admission_serialized_input,
    build_auction_result_serialized_input, build_deposit_note, build_deposit_submission_plan,
    build_heartbeat_cover_orders, build_note_consolidation_serialized_input,
    build_note_consolidation_submission_plan, build_order_submission, build_output_note,
    build_renewal_parent_cancel_submission_plan,
    build_settlement_output_withdrawal_submission_plan, build_settlement_submission_plan,
    build_settlement_witness, build_stwo_serialized_input, build_withdrawal_submission_plan,
    create_maker_attribution_artifact, create_order_ingress_receipt, create_recovery_artifact,
    decrypt_maker_attribution_artifact, decrypt_note_for_owner, decrypt_order_bundle,
    decrypt_order_share, decrypt_output_note_for_owner, decrypt_output_recovery_record,
    decrypt_recovery_artifact_payload, deposit_note_membership_witnesses_for_chain,
    deposit_note_root, derive_account_id, derive_order_cancellation_auth_tag,
    derive_order_cancellation_secret, derive_order_cancellation_tag, encrypt_note_for_owner,
    encrypt_output_note_for_owner, encrypt_output_recovery_record,
    heartbeat_cover_order_commitments, heartbeat_cover_order_count,
    maker_band_attribution_commitment, native_admission_message_hash,
    native_auction_result_message_hash, native_note_consolidation_message_hash,
    native_nullifier_message_hash, native_renewal_message_hash, native_settlement_message_hash,
    note_consolidation_commitment, note_consolidation_commitment_from_roots,
    note_consolidation_proof_message_hash_for_program,
    note_consolidation_proof_message_hash_from_statement,
    note_recognition_public_key_from_raw_key_hex, nullifier_proof_message_hash_for_program,
    nullifier_proof_message_hash_from_statement,
    nullifier_sparse_update_witnesses_for_consumed_inputs,
    nullifier_sparse_update_witnesses_for_nullifiers, output_note_merkle_proof,
    output_note_metadata_commitment, private_execution_key_registry_fingerprint,
    private_order_payload_commitment, proof_artifact_commitment, reconstruct_order_from_shares,
    renewal_child_uses_from_matched_witnesses, renewal_parent_cancel_marker_message_hash,
    renewal_proof_message_hash_for_program, renewal_proof_message_hash_from_statement,
    renewal_sparse_witnesses_for_child_uses, root_only_settlement_commitments,
    sanitize_order_submission_for_coordinator, settlement_note_root_after_deposit_chain,
    settlement_nullifier_root_after_history, settlement_output_withdrawal_message_hash,
    settlement_proof_message_hash, settlement_proof_message_hash_for_program,
    settlement_proof_message_hash_from_statement, settlement_state_transition_root,
    settlement_transcript_commitment, sign_note_consolidation_authorization,
    sign_order_authorization, validate_maker_attribution_receipt,
    validate_order_ingress_receipt_for_manifest,
    validate_order_ingress_receipt_for_manifest_with_secrets,
    validate_private_execution_key_registry_pin, verify_order_ingress_receipt,
    verify_order_ingress_receipt_with_secrets, verify_output_note_membership,
};
pub use error::ProtocolError;
pub use keys::{RecoverySeed, UserKeys, derive_user_keys};
pub use types::{
    ARTIFACT_AGGREGATION_POLICY_VERSION, ApprovalCallArguments, ArtifactAggregationPolicy, AssetId,
    AuctionOrderWitness, AuctionPrivacyGateWitness, Batch, BatchId, BatchLiquidityReport,
    BatchOrderSet, BatchShareContributions, BatchStatus, BatchSummary, ClaimWindowPolicy,
    ConsumedInput, CoordinatorStatus, DecryptedOrderShare, DeploymentContracts, DeploymentManifest,
    DepositCallArguments, DepositConfirmationList, DepositConfirmationRequest, DepositIntent,
    DepositRecord, DepositRecordList, DepositSubmissionPlan, DepositSyncStatus, EncryptedBlob,
    EncryptedMakerAttributionArtifact, EncryptedRecoveryPayload, FeeEntry, FundingRailAssetConfig,
    FundingRailCapabilities, FundingRailConfig, FundingRailKind, HiddenMakerCurve,
    MakerAttributionArtifactList, MakerAttributionBundle, MakerAttributionPlaintext,
    MakerAttributionReceipt, MakerBandAttribution, MakerBandFillAttribution, MakerCurvePoint,
    MatchedOrder, MatchedOrderWitness, MultiPairArtifactBundleList, MultiPairArtifactBundleSummary,
    Note, NoteCommitment, NoteConsolidationCallArguments, NoteConsolidationSubmissionPlan,
    NoteConsolidationWitness, NoteMembershipKind, NoteMembershipWitness, Nullifier,
    NullifierHistoryBatch, NullifierSparseUpdateWitness, OnchainSubmissionRecord,
    OrderCancellationAccepted, OrderCancellationRequest, OrderCommitment, OrderExecutionReport,
    OrderIngressReceipt, OrderIntent, OrderShare, OrderShareBundle, OrderSide, OrderSubmission,
    OrderSubmissionAccepted, OrderType, OutputCiphertextBundle, OutputNoteMerkleProof,
    OutputNoteRecord, OutputRecoveryRecord, OwnedOutputNotePayload, PairId, PreparedBatchStatus,
    PrivateExecutionKeyPrivateConfig, PrivateExecutionKeyPublicConfig, PrivateExecutionKeyRegistry,
    PrivateOrderPayload, ProductAssetConfig, ProductConfig, ProductPairConfig, ProofArtifactRecord,
    ProofJobStatus, PublicBatchSummary, PublicSettlementTranscript,
    PublishedBatchArtifactList, PublishedBatchArtifactSummary, PublishedBatchArtifacts,
    RENEWAL_PARENT_CANCEL_DOMAIN_HEX, RecoveryArtifact, RecoveryArtifactKind, RecoveryArtifactList,
    RecoveryArtifactUpload, RelayMode, RenewalChildUse, RenewalParentCancelCallArguments,
    RenewalParentCancelPlanRequest, RenewalParentCancelSubmissionPlan, RenewalStateHistoryBatch,
    RootOnlySettlementCommitments, SettlementCallArguments,
    SettlementOutputWithdrawalCallArguments, SettlementOutputWithdrawalSubmissionPlan,
    SettlementRootHistoryArchive, SettlementRootHistoryBatch, SettlementSubmissionPlan,
    SettlementTimestampUpdate, SettlementTranscript, SettlementWitness, SpendAuthorization,
    StarknetCall, StarknetPrivacyFundingRail, SubmittedOrderRecord, TimeInForce,
    TranscriptShapeMetadata, TrustedOrderIngressRequest, TrustedOrderIngressResponse, WalletEvent,
    WalletEventKind, WalletSnapshot, WithdrawalAmountBucketPlan, WithdrawalAmountBucketPolicy,
    WithdrawalCallArguments, WithdrawalRecord, WithdrawalRecordList, WithdrawalSubmissionPlan,
    WithdrawalWindowPlan, artifact_bundle_padded_count, artifact_epoch_bucket_end,
    artifact_epoch_bucket_start, asset_amount_scale, base_amount_affordable_for_quote,
    count_bucket_label, default_pair_fee_bps, default_withdrawal_amount_buckets,
    funding_input_set_commitment, funding_nullifier_set_commitment, is_conversion_pair,
    known_asset_decimals, nullifier_from_note_secret, output_bundle_bucket_size,
    output_bundle_count_bucket_label, plan_withdrawal_amount_bucket, plan_withdrawal_window,
    quote_amount_for_base_amount, renewal_cancel_auth_key_felt_from_raw_key_hex,
    renewal_cancel_authority_from_raw_key_hex,
    renewal_cancel_authority_from_renewal_cancel_auth_key_felt, renewal_child_nullifier,
    renewal_parent_cancel_marker, renewal_parent_commitment, renewal_parent_secret_commitment,
    spend_auth_key_felt_from_raw_key_hex, spend_authority_from_raw_key_hex,
    spend_authority_from_spend_auth_key_felt, transcript_shape_metadata,
    validate_transcript_shape_policy, withdraw_auth_key_felt_from_raw_key_hex,
    withdraw_authority_from_raw_key_hex, withdraw_authority_from_withdraw_auth_key_felt,
};
